# node-exporter is an optional component that collects host level metrics from the nodes
# in the cluster. This group of resources will require the 'hostaccess' level of privilege, which
# should only be granted to namespaces that administrators can access.
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: prometheus-node-exporter
  # You must grant hostaccess via:
  # oc adm policy add-scc-to-user -z prometheus-node-exporter -n [NAMESPCACE] hostaccess
  # in order for the node-exporter to access the host network and mount /proc and /sys from the host
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    name: prometheus-node-exporter
    labels:
      app: prometheus-node-exporter
      role: monitoring
    namespace: prom-monitoring
  spec:
    updateStrategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          name: prometheus-node-exporter
        name: prometheus-node-exporter
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9100"
      spec:
        serviceAccountName: prometheus-node-exporter
        hostNetwork: true
        hostPID: true
        containers:
        - image: openshift/prometheus-node-exporter:v0.15.2
          # Note: labels are renamed with V0.16.0 -> other dashboards needed!
          args:
          - "--path.procfs=/host/proc"
          - "--path.sysfs=/host/sys"
          - "--collector.filesystem.ignored-mount-points"
          - "^/(rootfs/)?(sys|proc|dev|host|etc|var|run).*"
          name: prometheus-node-exporter
          ports:
          - containerPort: 9100
            name: scrape
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            # minimal setting for cluster are sufficient
            cpu: 10m
            memory: 30Mi
            
          volumeMounts:
          - name: proc
            readOnly:  true
            mountPath: /host/proc
          - name: sys
            readOnly: true
            mountPath: /host/sys
        volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
